(function(){
  const style=document.createElement('style');style.textContent=`#runOverlay{position:fixed;inset:0;z-index:20;background:#0d0f13;color:#eee;display:none;flex-direction:column;max-width:680px;margin:auto}#runOverlay.open{display:flex}.runTop{padding:16px;background:#181b21;border-bottom:1px solid #2a2e37}.runStats{display:flex;justify-content:space-between;font-size:14px;margin-top:8px}.runHp{height:10px;background:#343944;border-radius:9px;overflow:hidden;margin-top:8px}.runHp i{display:block;height:100%;background:#c94f55}.runLog{flex:1;overflow:auto;padding:14px}.runLine{padding:8px 0;border-bottom:1px solid #262b34;line-height:1.45}.runBottom{padding:12px;background:#171a20;border-top:1px solid #292e37}.runChoices{position:absolute;inset:0;background:#000b;display:none;align-items:center;padding:18px}.runChoices.open{display:flex}.choiceBox{width:100%;background:#191c22;border:1px solid #454b58;border-radius:16px;padding:16px}.choiceBox h2{margin:0 0 12px}.runChoice{display:block;width:100%;text-align:left;margin:8px 0;padding:12px;border:1px solid #4d5562;border-radius:12px;background:#242a33;color:#fff}.runButton{width:100%;padding:12px;border:0;border-radius:12px;background:#9a7b37;color:#fff;font-weight:700}`;document.head.appendChild(style);
  const overlay=document.createElement('section');overlay.id='runOverlay';overlay.innerHTML=`<header class="runTop"><div class="title"><span>《說話之島：活過五分鐘》</span><button class="sound" id="runExit">離開</button></div><div class="runStats"><span>⏱ <b id="runTime">05:00</b></span><span>Lv.<b id="runLevel">1</b></span><span>💰 <b id="runGold">0</b></span></div><div class="runHp"><i id="runHpFill"></i></div><div class="runStats"><span>❤️ <b id="runHp">30/30</b></span><span>DPS <b id="runDps">0</b></span></div></header><main class="runLog" id="runLog"></main><footer class="runBottom"><button class="runButton" id="runStart">開始五分鐘遠征</button></footer><div class="runChoices" id="runChoices"><div class="choiceBox"><h2 id="choiceTitle">LEVEL UP</h2><div id="choiceList"></div></div></div>`;document.body.appendChild(overlay);
  const $=id=>document.getElementById(id),log=$('runLog');let run=null,timer=null,tick=null;
  const upgrades=[['🗡️ 亂揮一通','攻擊 +30%',r=>r.atk*=1.3],['🧪 過期紅水','每 10 秒恢復 2 HP',r=>r.regen+=2],['🌳 樹上騎士證照','每 15 秒造成 20 傷害',r=>r.knight=true],['📜 哥布林無證執照','怪物生成間隔縮短，但金幣 +50%',r=>{r.spawn=.8;r.gold*=1.5}],['🥖 麵包盾牌','受到傷害 -25%',r=>r.guard*=.75],['🐺 狼工會仲裁','每擊敗 5 隻怪物恢復 5 HP',r=>r.healKills=5]];
  function write(t,c=''){let d=document.createElement('div');d.className='runLine '+c;d.textContent=t;log.appendChild(d);log.scrollTop=log.scrollHeight}
  function refresh(){if(!run)return;let left=Math.max(0,300-run.sec),m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');$('runTime').textContent=`${m}:${s}`;$('runLevel').textContent=run.level;$('runGold').textContent=Math.floor(run.gold);$('runHp').textContent=`${Math.ceil(run.hp)}/${run.maxHp}`;$('runHpFill').style.width=Math.max(0,run.hp/run.maxHp*100)+'%';$('runDps').textContent=Math.round(run.atk)}
  function choices(){if(run.paused||run.boss)return;run.paused=true;let list=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);$('choiceList').innerHTML=list.map((u,i)=>`<button class="runChoice" data-i="${i}"><b>${u[0]}</b><br><small>${u[1]}</small></button>`).join('');$('runChoices').classList.add('open');$('choiceList').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{list[i][2](run);write(`✨ 你選擇：${list[i][0]}（${list[i][1]}）`,'good');$('runChoices').classList.remove('open');run.paused=false;refresh()})}
  function spawn(){let keys=Object.keys(MONSTERS),id=keys[Math.floor(Math.random()*keys.length)],m=MONSTERS[id],count=run.sec<60?1:run.sec<180?2:3;for(let i=0;i<count;i++)run.enemies.push({name:m.name,hp:m.hp*(1+run.sec/240),attack:m.attack});write(`👹 ${m.name} ×${count} 出現。`)}
  function fight(){if(run.paused)return;if(run.sec>=300&&!run.boss){run.boss={name:'村長家的雞',hp:500,maxHp:500};write('🐔 Lv.??? 村長家的雞出現了！\n村長：「不要傷害牠！」','boss')};if(run.boss){let d=run.atk+Math.floor(Math.random()*5);run.boss.hp-=d;run.hp=Math.max(0,run.hp-4);write(`⚔️ 鐵劍 -${d}　🐔 雞剩餘 HP ${Math.max(0,Math.ceil(run.boss.hp))}`);if(run.boss.hp<=0)return finish(true);return}if(!run.enemies.length)spawn();let d=run.atk+Math.floor(Math.random()*4),target=run.enemies[0];target.hp-=d;write(`⚔️ 自動攻擊 ${target.name} -${d}`);run.hp=Math.max(0,run.hp-run.enemies.reduce((n,e)=>n+e.attack,0)*run.guard);if(run.sec%10===0)run.hp=Math.min(run.maxHp,run.hp+run.regen);if(run.knight&&run.sec>0&&run.sec%15===0){let kd=20;run.enemies[0].hp-=kd;write(`🌳 樹上騎士墜落 -${kd}`)}if(target.hp<=0){run.enemies.shift();run.exp+=target.attack+3;run.gold+=target.attack;run.kills++;write(`💥 擊敗${target.name}　EXP +${target.attack+3}`);if(run.kills%run.healKills===0)run.hp=Math.min(run.maxHp,run.hp+5)}if(run.exp>=run.next){run.exp-=run.next;run.level++;run.next=Math.floor(run.next*1.45);run.maxHp+=6;run.hp=run.maxHp;choices()}if(run.hp<=0)return finish(false)}
  function start(){run={sec:0,level:1,exp:0,next:20,hp:player.maxHp,maxHp:player.maxHp,atk:Math.max(2,player.baseAttack+ITEMS[player.equipment.weapon].attack),gold:0,regen:0,knight:false,guard:1,spawn:1,healKills:999,kills:0,enemies:[],boss:null,paused:false};log.innerHTML='';$('runStart').style.display='none';overlay.classList.add('open');write('🚪 你進入說話之島遠征。怪物會自己找上門。');refresh();tick=setInterval(()=>{if(!run||run.paused)return;run.sec++;if(run.sec===60||run.sec===120||run.sec===180||run.sec===270)write('🎭 荒謬事件：某個不該出現的東西正在靠近……','good');if(run.sec%20===0)choices();fight();refresh()},1000)}
  function finish(win){clearInterval(tick);clearInterval(timer);if(win){write('🏆 你擊敗了村長家的雞！','good');write(`本局結算：Lv.${run.level}、擊殺 ${run.kills}、獲得 ${Math.floor(run.gold)} 金幣。`,'good')}else{write('💀 你在五分鐘內失去意識。','boss');write(`本局結算：存活 ${run.sec} 秒、擊殺 ${run.kills}。`)}$('runStart').textContent='再開一局';$('runStart').style.display='block';refresh()}
  function addEntry(){if(document.querySelector('#startRunButton'))return;let panel=document.querySelector('.explore');if(!panel)return;let b=document.createElement('button');b.id='startRunButton';b.className='btn';b.innerHTML='⚔️<br>五分鐘遠征';b.onclick=()=>start();panel.querySelector('.grid')?.appendChild(b)}
  $('runStart').onclick=start;$('runExit').onclick=()=>{clearInterval(tick);overlay.classList.remove('open');run=null};
  const oldRender=window.render;window.render=function(){oldRender();addEntry()};addEntry();
})();
