import { createMinimalWorld } from '../src/content/minimalWorld.js';
import { TextObserver } from '../src/presentation/textObserver.js';
import { labelOf } from '../src/presentation/labels.js';
import { buildingDefinitions } from '../src/content/buildingDefinitions.js';
import { activityDefinitions } from '../src/activity/activityDefinitions.js';

const observer = new TextObserver(); let world = createMinimalWorld(); let timer = null; let currentTab = 'overview';
const $ = id => document.getElementById(id); const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const resourceNames = { food: '食物', wood: '木材', stone: '石材', gold: '金幣', medicine: '藥品' }; const professionNames = { FARMER: '農夫', HUNTER: '獵人', MERCHANT: '商人', GUARD: '守衛', WOODCUTTER: '樵夫', STONECUTTER: '石匠', HEALER: '藥師', LABORER: '勞工' };
const reasonNames = { INSUFFICIENT_RESOURCES: '資源不足', INSUFFICIENT_ENERGY: '能量不足', ALREADY_BUILT: '已經建造', SETTLEMENT_LEVEL_REQUIRED: '城鎮等級不足', ACTIVITY_IN_PROGRESS: '已有行動進行中' };
const costText = cost => Object.entries(cost ?? {}).map(([key, value]) => `${resourceNames[key] ?? key} ${value}`).join('、') || '無消耗';
const setNotice = text => { const box = $('interaction-box'); if (box) box.textContent = text; };
function choiceMarkup(event, type) { if (!event) return '<span class="muted">目前沒有待處理事件。</span>'; return `<strong>${escapeHtml(event.title)}</strong><p class="muted">${escapeHtml(event.description)}</p><div class="event-choice">${event.options.map(option => `<button data-${type}-option="${escapeHtml(option.id)}"><span>${escapeHtml(option.label)}</span><span class="cost">${escapeHtml(costText(option.cost))}${option.costEnergy ? `｜能量 ${option.costEnergy}` : ''}</span></button>`).join('')}</div>`; }
function render() {
  const view = observer.describe(world); const player = world.entities.get('player'); const settlement = view.settlement; const currentEvent = world.currentEvent(); const residentEvent = world.currentResidentEvent();
  $('world-status').textContent = `${labelOf(world.mode)} · ${view.worldMinutes} 分鐘`;
  $('summary').innerHTML = [['時間', `第 ${Math.floor(view.worldMinutes / 1440) + 1} 天 ${view.worldMinutes % 1440} 分`], ['城鎮', `等級 ${settlement.level}`], ['人口', `${view.population?.alive ?? 0}／住房 ${settlement.housing}`], ['繁榮', settlement.prosperity], ['安全', settlement.safety], ['士氣', settlement.morale], ['玩家能量', `${player?.energy ?? 100}／${player?.maxEnergy ?? 100}`], ['威脅壓力', world.threat.pressure]].map(([name, value]) => `<div class="metric"><span>${name}</span><strong>${escapeHtml(value)}</strong></div>`).join('');
  $('town-resources').innerHTML = Object.entries(settlement.resources).map(([key, value]) => `<div class="metric"><span>${resourceNames[key] ?? key}</span><strong>${Math.floor(value)}／${settlement.capacities[key] ?? '∞'}</strong></div>`).join('');
  $('buildings').innerHTML = buildingDefinitions.map(definition => { const built = world.buildings.has(definition.id); const available = settlement.level >= definition.level && Object.entries(definition.cost).every(([key, value]) => (settlement.resources[key] ?? 0) >= value); return `<div class="building"><div><strong>${definition.name}</strong><span class="small">${built ? '已建造' : `需求：等級 ${definition.level} · ${costText(definition.cost)}`}</span></div><button data-build="${definition.id}" ${built || !available ? 'disabled' : ''}>${built ? '完成' : '建造'}</button></div>`; }).join('');
  $('activities').innerHTML = Object.values(activityDefinitions).map(definition => `<div class="row"><div><strong>${definition.name}</strong><span class="small">${definition.description}｜能量 ${definition.energy}</span></div><button data-activity="${definition.id}" ${world.activities.progress() ? 'disabled' : ''}>開始</button></div>`).join('');
  const activity = world.activities.progress(); $('activity-progress').innerHTML = activity ? `<strong>${activityDefinitions[activity.activityId].name}</strong><div class="progress"><div style="width:${activity.ratio * 100}%"></div></div><span class="small">進度 ${Math.floor(activity.ratio * 100)}%</span>` : '選擇一項行動協助村落。';
  $('interactions').innerHTML = view.entities.filter(entity => entity.type === 'NPC' && entity.zoneId === 'village').map(entity => { const full = world.entities.get(entity.id); const contribution = Object.entries(world.economy.contributions[entity.id] ?? {}).map(([key, value]) => `${resourceNames[key] ?? key} ${Math.floor(value)}`).join('、') || '尚無產出紀錄'; const relationship = player?.relationships?.[entity.id] ?? 0; return `<div class="resident-row"><div><strong>${escapeHtml(entity.name)}</strong><span class="small">${professionNames[entity.profession] ?? '居民'}｜信任 ${relationship}</span><span class="small">貢獻：${contribution}</span></div><div class="button-row"><button data-inspect="${entity.id}">查看</button><button data-talk="${entity.id}">交談</button><button data-request="${entity.id}">請求</button></div></div>`; }).join('') || '<span class="muted">目前沒有可交談的居民</span>';
  $('overview-event').innerHTML = choiceMarkup(currentEvent, 'event') !== '<span class="muted">目前沒有待處理事件。</span>' ? choiceMarkup(currentEvent, 'event') : choiceMarkup(residentEvent, 'resident');
  $('event-center').innerHTML = currentEvent ? choiceMarkup(currentEvent, 'event') : residentEvent ? choiceMarkup(residentEvent, 'resident') : '<span class="muted">目前沒有待處理事件。</span>';
  $('events-preview').innerHTML = view.recentEvents.slice(-4).map(event => `<div class="event"><time>@${event.worldTime}</time>${escapeHtml(labelOf(event.type))}</div>`).join('') || '<span class="muted">尚無事件</span>';
  $('event-log').innerHTML = view.recentEvents.map(event => `<div class="event"><time>@${event.worldTime}</time>${escapeHtml(labelOf(event.type))}</div>`).join('') || '<span class="muted">尚無事件</span>';
  $('toggle').textContent = world.mode === 'RUNNING' ? '暫停' : '啟動'; document.querySelectorAll('.screen').forEach(screen => screen.classList.toggle('active', screen.id === currentTab)); document.querySelectorAll('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.tab === currentTab));
}
function tick() { if (world.mode === 'RUNNING') { world.step(); render(); } } function restartTimer() { clearInterval(timer); timer = setInterval(tick, 500); }
$('toggle').addEventListener('click', () => { if (world.mode === 'RUNNING') world.pause(); else if (world.mode === 'PAUSED') world.resume(); else world.start(); render(); }); $('step').addEventListener('click', () => { if (world.mode === 'STOPPED') world.start(); world.pause(); world.step(); render(); }); $('reset').addEventListener('click', () => { world = createMinimalWorld(); setNotice('世界已重新開始。'); render(); });
document.querySelector('.bottom-nav').addEventListener('click', event => { if (!event.target.dataset.tab) return; currentTab = event.target.dataset.tab; render(); });
$('activities').addEventListener('click', event => { const id = event.target.closest('[data-activity]')?.dataset.activity; if (!id) return; const result = world.startActivity(id); setNotice(result.ok ? `已開始：${activityDefinitions[id].name}` : `無法開始：${reasonNames[result.reason] ?? result.reason}`); render(); });
$('buildings').addEventListener('click', event => { const id = event.target.closest('[data-build]')?.dataset.build; if (!id) return; const result = world.build(id); setNotice(result.ok ? `已建造：${buildingDefinitions.find(item => item.id === id).name}` : `無法建造：${reasonNames[result.reason] ?? result.reason}`); render(); });
$('interactions').addEventListener('click', event => { const target = event.target.closest('button'); const targetId = target?.dataset.talk || target?.dataset.inspect || target?.dataset.request; if (!targetId) return; if (target.dataset.talk) setNotice(world.talk('player', targetId).reply); else if (target.dataset.inspect) { const result = world.inspectResident(targetId); setNotice(result.ok ? `${result.resident.name}｜職業：${professionNames[result.resident.profession] ?? result.resident.profession}\n${result.resident.personality ?? ''}\n${result.resident.background ?? ''}\n請求：${result.resident.request?.text ?? '目前沒有請求'}` : '無法查看這名居民。'); } else { const result = world.acceptResidentRequest('player', targetId); setNotice(result.ok ? `已接受請求：${result.text}` : `無法接受：${result.reason}`); } render(); });
function resolveChoice(event) { const target = event.target.closest('button'); if (!target) return; if (target.dataset.eventOption) setNotice(world.resolveEvent(target.dataset.eventOption).ok ? '事件已處理。' : '目前無法採用這個方案。'); if (target.dataset.residentOption) setNotice(world.resolveResidentEvent(target.dataset.residentOption).ok ? '居民事件已處理。' : '目前無法採用這個方案。'); render(); }
$('overview-event').addEventListener('click', resolveChoice); $('event-center').addEventListener('click', resolveChoice); restartTimer(); render();
